name: opencv-em-script

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: git submodule update --init
    - run: sudo apt-get update && sudo apt install ninja-build
    - run: ./build.sh linux
    - run: echo "Done!"